Update requirements.txt - adding pymongo==4.8 as from some other dependency the lastest pymongo@4.9 is being pulled, and this 4.9 doesn't have _QUERY_OPTIONS
Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/app/unzipper/__main__.py", line 11, in <module> from .helpers.start import check_logs, dl_thumbs, set_boot_time, removal File "/app/unzipper/helpers/start.py", line 12, in <module> from unzipper.modules.callbacks import download File "/app/unzipper/modules/callbacks.py", line 21, in <module> from unzipper.helpers.database import ( File "/app/unzipper/helpers/database.py", line 3, in <module> from motor.motor_asyncio import AsyncIOMotorClient File "/venv/lib/python3.12/site-packages/motor/motor_asyncio.py", line 16, in <module> from . import core, motor_gridfs File "/venv/lib/python3.12/site-packages/motor/core.py", line 30, in <module> from pymongo.cursor import _QUERY_OPTIONS, Cursor, RawBatchCursor ImportError: cannot import name '_QUERY_OPTIONS' from 'pymongo.cursor' (/venv/lib/python3.12/site-packages/pymongo/cursor.py)